force-app/main/default/objects/Scan_Result__c/Scan_Result__c.object-meta.xml
<CustomObject>
    <label>Scan Result</label>
    <nameField>
        <label>Scanned Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scan Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scan_Result__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scan_Result__c/fields/Shelf_Scan__c.field-meta.xml
<CustomField>
    <fullName>Shelf_Scan__c</fullName>
    <label>Shelf Scan</label>
    <referenceTo>Shelf_Scan__c</referenceTo>
    <relationshipLabel>Scan Results</relationshipLabel>
    <relationshipName>Scan_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shelf_Scan__c/Shelf_Scan__c.object-meta.xml
<CustomObject>
    <label>Shelf Scan</label>
    <nameField>
        <displayFormat>SCAN-{00000}</displayFormat>
        <label>Shelf Scan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shelf Scans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ShelfScanner.cls
public class ShelfScanner {
    
    @AuraEnabled
    public static Einstein_PredictionResult detectShelfObjects(String modelId, String base64){
        Einstein_PredictionService service = new Einstein_PredictionService(Einstein_PredictionService.Types.IMAGE_DETECTION);
        Einstein_PredictionResult result = service.detectImageBase64(modelId, base64, 0, '');
        return result;
    }
    
    @AuraEnabled
    public static void storeScanResults(String jsonString) {
        List<Object> scanResults = (List<Object>)JSON.deserializeUntyped(jsonString);
        System.debug(scanResults);
        Shelf_Scan__c scan = new Shelf_Scan__c();
        insert scan;
        List<Scan_Result__c> storeResults = new List<Scan_Result__c>();
        for (Object obj : scanResults) {
            Map<String, Object> result = (Map<String, Object>)obj;
            Scan_Result__c storeResult = new Scan_Result__c(Name=result.get('label').toString(), Count__c=(Decimal)result.get('count'), Shelf_Scan__c=scan.Id);
            storeResults.add(storeResult);
        }
        insert storeResults;
    }
    
}